#import RPi.GPIO as GPIO
from EmulatorGUI import GPIO
import time

#SETAR O MODO PARA PINAGEM "DIGITAL" JÁ QUE SE TRATA DE UM EMULADOR. PINAGEM FISICA -> (GPIO.BOARD)
GPIO.setmode(GPIO.BCM)

#SETAR QUAL PINO VAI UTILIZAR E QUAL VAI SER O MODO DELE. NO CASO, MODO DE SAÍDA.
GPIO.setup(12, GPIO.OUT)

#IGNORAR WARNINGS
GPIO.setwarnings(False)

#SAÍDA DE INFORMAÇÃO -> OUTPUT(PINO, TRUE/FALSE). TRUE PARA NÍVEL ALTO, FALSO PARA NÍVEL BAIXO.
GPIO.output(12, True)
time.sleep(5) #SLEEP É EM SEGUNDOS
GPIO.output(12, False)



